spring.application.name=inno
# Base de données
spring.datasource.url=jdbc:postgresql://localhost:5432/inno_db
spring.datasource.username=postgres
spring.datasource.password=ramzibir3li
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT 
jwt.secret=dGhpcyBpcyBhIHN1ZmZpY2llbnRseSBsb25nIHNlY3JldCBrZXkgZm9yIElubm9CdXNpbmVzcw==
jwt.expiration=86400000
# Origine autorisée pour le CORS (le front Angular en dev)
app.cors.allowed-origin=http://localhost:4200
# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.try-it-out-enabled=true
# File storage
file.upload-dir=./uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=30MB